name: Build Python venv using caching

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('dependencies/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Create and install (if needed)
        run: |
          if [ ! -d ".venv" ]; then
            python -m venv .venv
            source .venv/bin/activate
            pip install -r venv/requirements.txt
          else
            echo "Using cached virtual environment."
          fi

      - name: Verify install
        run: |
          source .venv/bin/activate
          python -c "import numpy; print(numpy.__version__)"
