name: Inefficient workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dependencies/requirements.txt

      - name: Verify install
        run: |
          source .venv/bin/activate
          python -c "import numpy; print(numpy.__version__)"
