name: Inefficient Dataset Download

on:
  workflow_dispatch:

jobs:
  dataset-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download large file
        run: |
          mkdir -p data
          echo "Downloading test file ..."
          wget -O data/1GB.bin https://ash-speed.hetzner.com/1GB.bin

      - name: List data directory
        run: ls -lh data
