name: Build Python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run mathlib.py
        run: python python/mathlib.py
        
      - name: Run tests
        run: python python/test_mathlib.py
