name: Build Python

on:
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11.0, 3.12.0, 3.13.0]
        architecture: [x64, ARM64]
        exclude:
          - os: windows-latest
            architecture: arm64
          - os: macos-latest
            architecture: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Run mathlib.py
        run: python python/mathlib.py
        
      - name: Run tests
        run: python python/test_mathlib.py
