name: Inefficient Dataset Download

on:
  workflow_dispatch:

jobs:
  dataset-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Always download dataset
        run: |
          mkdir -p data
          echo "Downloading dataset..."
          wget -O data/AirQualityUCI.zip https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip

      - name: List data directory
        run: ls -lh data
