name: Conditional execution

on:
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.11.0, 3.12.0, 3.13.0]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run mathlib.py
        run: python python/mathlib.py

      - name: Run tests (skip for 3.13.0)
        if: matrix.python-version != '3.13.0'
        run: python python/test_mathlib.py

      - name: Extra step for Python 3.12.0
        if: matrix.python-version == '3.12.0'
        run: echo "Running extra step for Python 3.12.0"

#     - name: Introduce failure
#       run: exit 1

#     - name: This runs on failure
#       if: failure()
#       run: echo "The previous step failed, so this step is running."

#     - name: This always runs
#       if: always()
#       run: echo "This step runs regardless of previous step outcome."
