name: Hello World with Variable

on:
  workflow_dispatch:

jobs:
  Hello:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello from an environment variable"
    steps:
      - name: Run a one-line script
        run: echo $GREETING
      - name: Run a multi-line script
        run: |
          echo "Starting script..."
          echo $GREETING
          echo "Script complete!"
