name: Least privilege

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.0

      - name: Run mathlib.py
        run: python python/mathlib.py

      - name: Run tests
        run: python python/test_mathlib.py

  create-issue:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create issue from template
        uses: JasonEtco/create-an-issue@v2.9.2
        with:
          filename: .github/actions issue template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
