name: Manual workflow inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'world'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Hello, ${{ inputs.name }}!"
          else
            echo "Triggered automatically. Skipping manual inputs."
          fi
