name: Variable-driven build

on:
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  RUN_TESTS: 'false'  # Environment variables are always strings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Conditional Message
        if: env.NODE_VERSION == '18'
        run: echo "You're using Node 18!"
        
      - name: Run mathlib tests
        if: env.RUN_TESTS == 'true'
        run: node javascript/test_mathlib.js
